parameters:
#    application_paypal.example.class: Application\PaypalBundle\Example

services:
#    application_paypal.example:
#        class: %application_paypal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
