#==================================================
#  PAYPAL
#==================================================
jms_payment_core:
    secret: %jmspaypal.secret% 
    
jms_payment_paypal:
    username: %jmspaypal.username% 
    password: %jmspaypal.password% 
    signature: %jmspaypal.signature% 
    debug: true
    #/false # when true, connect to PayPal sandbox; uses kernel debug value when not specified
 
#sensio_framework_extra:
#    view:
#        annotations: false

                   
#swiftmailer:
#    disable_delivery:  false

jms_di_extra:
    locations:
        all_bundles: false
        bundles: [ApplicationPaypalBundle]
        directories: ["%kernel.root_dir%/../src"]
    automatic_controller_injections:
        properties:
            request: "@request"
            router: "@router"
        method_calls:
            setRouter: ["@router"]
            
   