  
payum:
    contexts:
        simple_purchase_paypal_express_checkout:
            paypal_express_checkout_nvp_payment:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            filesystem_storage:
                model_class: Application\PaypalExpressCheckoutBundle\Model\PaymentDetails
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id
                
        simple_purchase_paypal_express_checkout_doctrine:
            paypal_express_checkout_nvp_payment:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            doctrine_storage:
                driver: orm
                model_class: Application\PaypalExpressCheckoutBundle\Entity\PaymentDetails
                
        simple_recurring_payment_paypal_express_checkout:
            paypal_express_checkout_nvp_payment:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            filesystem_storage:
                model_class: Application\PaypalExpressCheckoutBundle\Model\PaymentDetails
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id

        simple_purchase_paypal_pro:
            paypal_pro_checkout_nvp_payment:
                api:
                    options:
                        username: %paypal.pro_checkout.username%
                        password: %paypal.pro_checkout.password%
                        partner:  %paypal.pro_checkout.partner%
                        vendor:   %paypal.pro_checkout.vendor%
                        sandbox: true
                
        simple_purchase_authorize_net:
            authorize_net_aim_payment:
                api:
                    options:
                        login_id: %authorize_net.login_id%
                        transaction_key: %authorize_net.transaction_key%
                        sandbox: true

            filesystem_storage:
                model_class: Application\PaymentBundle\Model\AuthorizeNetInstruction
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id

        simple_purchase_be2bill:
            be2bill_payment:
                api:
                    options:
                        identifier: %be2bill.identifier%
                        password: %be2bill.password%
                        sandbox: true

            filesystem_storage:
                model_class: Application\PaymentBundle\Model\Be2BillInstruction
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id
                
        simple_purchase_paypal_express_via_ominpay:
            omnipay_payment:
                type: PayPal_Express
                options:
                    username:  %paypal.express_checkout.username%
                    password:  %paypal.express_checkout.password%
                    signature: %paypal.express_checkout.signature%
                    testMode: true
                    
            filesystem_storage:
                model_class: Application\PaymentBundle\Model\OmnipayInstruction
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id
