#==================================================
#  PAYPAL
#==================================================
         
 /* 
payum:
    contexts:
        simple_purchase_paypal_express_checkout:
            paypal_express_checkout_nvp_payment:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            filesystem_storage:
                model_class: Application\PaypalExpressCheckoutBundle\Model\PaymentDetails
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id
                
        simple_purchase_paypal_express_checkout_doctrine:
            paypal_express_checkout_nvp_payment:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            doctrine_storage:
                driver: orm
                model_class: Application\PaypalExpressCheckoutBundle\Entity\PaymentDetails
                
 */   
        