imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
     # Sonata Bundles
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_doctrine.yml }
    - { resource: sonata/sonata_user.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_news.yml }
  #  - { resource: sonata/sonata_page.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
   # form:
    #   resources:
     #       - "BraincraftedBootstrapBundle:Form:form_div_layout.html.twig"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar


#==================================================
#  DOCTRINE
#==================================================
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
        #mapping_types:
        #     enum: string
        types:
           json: Sonata\Doctrine\Types\JsonType
    orm:
      #  entity_managers:
       #     default:
       #         mappings:
       #             SonataMediaBundle: ~
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            payum_paypal_express_checkout_nvp:
                is_bundle: false
                type: xml
                dir: %kernel.root_dir%/../vendor/payum/paypal-express-checkout-nvp/src/Payum/Paypal/ExpressCheckout/Nvp/Bridge/Doctrine/Resources/mapping
                prefix: Payum\Paypal\ExpressCheckout\Nvp\Bridge\Doctrine\Entity
        #dql:
        #    string_functions:
         #               GroupConcat: DoctrineExtensions\Query\Mysql\GroupConcat
         
         
         
# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }


#==================================================
#  FOSUSER
# pour les commandes fos:user:create
#==================================================
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User 
    group:
      group_class: Application\Sonata\UserBundle\Entity\Group 
    profile:  # Authentication Form
        form:
            type:               fos_user_profile
            name:               fos_user_profile_form
            validation_groups:  [Authentication] # Please note : this is not the default value
            
            # On utilise twig_swift pour pouvoir envoyer un email en HTML
    service:
        mailer: fos_user.mailer.twig_swift
    # Permet de renseigner le nouveau formulaire d'inscription
    registration:
        form:
          # default form
            type: fos_user_registration
        # Permet la validation automatique du compte par envoi d'un email
        confirmation:
            enabled:    true
            from_email:
                # Adresse de l'expediteur
                address:        noreply@monsiteweb.com
                # Nom de l'expediteur
                sender_name:    Admin de monsiteweb.com
        # Permet de définir le template de l'email à envoyer (en html)
        #email:
        #    template: MyAppMonBundle:User:registration.email.twig
 
   # registration:
   #   form:
   #     type: myapp_user_registration



#==================================================
#  KNP_PAGINATOR ET SORT
#==================================================
    
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: false                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
             pagination: BraincraftedBootstrapBundle:Pagination:pagination.html.twig
   # template:
      # sliding pagination controls template
      #pagination: ApplicationCertificatsBundle:pagination:twitter_bootstrap_pagination.html.twig
       # sliding pagination controls template
      #sortable: ApplicationCertificatsBundle:pagination:sortable_link.html.twig 
      # sort link template
      
      
knp_menu:
       twig:
            template: "BraincraftedBootstrapBundle:Menu:menu.html.twig"
            
            
            
#==================================================
#  TINYMCE
#==================================================

stfalcon_tinymce:
        include_jquery: false
        tinymce_jquery: true
        textarea_class: "tinymce"
        theme:
            # Simple theme: same as default theme
            advanced:
                theme: "advanced"
                plugins: "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template"
                theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect"
                theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor"
                theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen"
                theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak"
                theme_advanced_toolbar_location: "top"
                theme_advanced_toolbar_align: "left"
                theme_advanced_statusbar_location: "bottom"
                theme_advanced_resizing: true
            # Medium number of enabled plugins + spellchecker
            simple:
                mode: "textareas"
                theme: "advanced"
                theme_advanced_buttons1: "mylistbox,mysplitbutton,bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,undo,redo,link,unlink"
                theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor"
                theme_advanced_buttons3: ""
                theme_advanced_toolbar_location: "top"
                theme_advanced_toolbar_align: "left"
                theme_advanced_statusbar_location: "bottom"
                plugins: "fullscreen"
                theme_advanced_buttons1_add: "fullscreen"
                theme_advanced_resizing:           true,
            # Advanced theme with almost all enabled plugins
        
            medium:
                mode: "textareas"
                theme: "advanced"
                plugins: "table,advhr,advlink,paste,xhtmlxtras,spellchecker"
                theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,forecolor,backcolor,|,hr,removeformat,|,sub,sup,|,spellchecker"
                theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,bullist,numlist,|,undo,redo,|,link,unlink,anchor,cleanup,code,|,tablecontrols"
                theme_advanced_buttons3: ""
                theme_advanced_toolbar_location: "top"
                theme_advanced_toolbar_align: "left"
                theme_advanced_statusbar_location: ""
                paste_auto_cleanup_on_paste: true
                plugins: "fullscreen"
                theme_advanced_buttons1_add: "fullscreen"
                theme_advanced_resizing:           true,
          
                spellchecker_languages: "+English=en,Dutch=nl"
            # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
            bbcode:
                mode: "none"
                theme: "advanced"
                plugins: "bbcode"
                theme_advanced_buttons1: "bold,italic,underline,undo,redo,link,unlink,image,forecolor,styleselect,removeformat,cleanup,code"
                theme_advanced_buttons2: ""
                theme_advanced_buttons3: ""
                theme_advanced_toolbar_location: "bottom"
                theme_advanced_toolbar_align: "center"
                theme_advanced_styles: "Code=codeStyle;Quote=quoteStyle"
                entity_encoding: "raw"
                add_unload_trigger: false
                remove_linebreaks: false
                inline_styles: false
                convert_fonts_to_spans: false
  
#==================================================
#  PAYPAL
#==================================================
jms_payment_core:
    secret: someMR157ROghsw0rd
    
jms_payment_paypal:
    username: test_1357225775_per@gmail.com 
    password: testtest 
    signature: signature
    debug: true
    #/false # when true, connect to PayPal sandbox; uses kernel debug value when not specified

sensio_framework_extra:
    view:
        annotations: false

 
#swiftmailer:
#    disable_delivery:  false

jms_di_extra:
    locations:
        all_bundles: false
        bundles: [ApplicationPaypalBundle]
        directories: ["%kernel.root_dir%/../src"]
    automatic_controller_injections:
        properties:
            request: "@request"
            router: "@router"
        method_calls:
            setRouter: ["@router"]
            
            
          
  
payum:
    contexts:
        simple_purchase_paypal_express_checkout:
            paypal_express_checkout_nvp_payment:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            filesystem_storage:
                model_class: Application/PaypalBundle\Model\PaymentDetails
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id
                
        simple_purchase_paypal_express_checkout_doctrine:
            paypal_express_checkout_nvp_payment:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            doctrine_storage:
                driver: orm
                model_class: Application/PaypalBundle\Entity\PaymentDetails
                
        simple_purchase_authorize_net:
            authorize_net_aim_payment:
                api:
                    options:
                        login_id: %authorize_net.login_id%
                        transaction_key: %authorize_net.transaction_key%
                        sandbox: true

            filesystem_storage:
                model_class: Application/PaypalBundle\Model\AuthorizeNetInstruction
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id

        simple_purchase_be2bill:
            be2bill_payment:
                api:
                    options:
                        identifier: %be2bill.identifier%
                        password: %be2bill.password%
                        sandbox: true

            filesystem_storage:
                model_class: Application/PaypalBundle\Model\Be2BillInstruction
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id
                
        simple_purchase_paypal_express_via_ominpay:
            omnipay_payment:
                type: PayPal_Express
                options:
                    username:  %paypal.express_checkout.username%
                    password:  %paypal.express_checkout.password%
                    signature: %paypal.express_checkout.signature%
                    testMode: true
                    
            filesystem_storage:
                model_class: Application/PaypalBundle\Model\OmnipayInstruction
                storage_dir: %kernel.root_dir%/Resources/payments
       
                
                id_property: id
                
                
                     
    
payum:
    contexts:
        simple_purchase_paypal_express_checkout:
            paypal_express_checkout_nvp_payment:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            filesystem_storage:
                model_class: Application\PaypalExpressCheckoutBundle\Model\PaymentDetails
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id
                
        simple_purchase_paypal_express_checkout_doctrine:
            paypal_express_checkout_nvp_payment:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true

            doctrine_storage:
                driver: orm
                model_class: Application\PaypalExpressCheckoutBundle\Entity\PaymentDetails
                
        simple_purchase_authorize_net:
            authorize_net_aim_payment:
                api:
                    options:
                        login_id: %authorize_net.login_id%
                        transaction_key: %authorize_net.transaction_key%
                        sandbox: true

            filesystem_storage:
                model_class: Application\PaymentBundle\Model\AuthorizeNetInstruction
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id

        simple_purchase_be2bill:
            be2bill_payment:
                api:
                    options:
                        identifier: %be2bill.identifier%
                        password: %be2bill.password%
                        sandbox: true

            filesystem_storage:
                model_class: Application\PaymentBundle\Model\Be2BillInstruction
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id
                
        simple_purchase_paypal_express_via_ominpay:
            omnipay_payment:
                type: PayPal_Express
                options:
                    username:  %paypal.express_checkout.username%
                    password:  %paypal.express_checkout.password%
                    signature: %paypal.express_checkout.signature%
                    testMode: true
                    
            filesystem_storage:
                model_class: Application\PaymentBundle\Model\OmnipayInstruction
                storage_dir: %kernel.root_dir%/Resources/payments
                id_property: id