#application_paypal_express_checkout:
#    resource: "@ApplicationPaypalExpressCheckoutBundle/Resources/config/routing.yml"
#    prefix:   /payum

#application_payment:
#    resource: "@ApplicationPaymentBundle/Controller/"
#    type:     annotation
#    prefix:   /

application_test:
    resource: "@ApplicationTestBundle/Resources/config/routing.yml"
    prefix:   /
    
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
 
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
 
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
 
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
 
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
 
soanata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
    
    
news:
    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /news
    
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery
   
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
    
  