parameters:
#    acme_payment.example.class: Acme\PaymentBundle\Example

services:
#    acme_payment.example:
#        class: %acme_payment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
