services:
    application_sonata_news.twig.extension:
        class: Application\Sonata\NewsBundle\Twig\Extensions\ApplicationSonataNewsExtension
        tags:
            - { name: twig.extension }


    sonata.news.manager.post:
       class: Application\Sonata\NewsBundle\Entity\PostManager
       
            
            
   