parameters:
#    application_relations.example.class: Application\RelationsBundle\Example

services:
#    application_relations.example:
#        class: %application_relations.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
