<?php

namespace Application\PaypalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaypalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaypalRepository extends EntityRepository
{
}
